### ISSUE TITLE
Incorrect tag used for quadruple compressed andesite cobble gen.

### ISSUE THREAD

**Issue by deathrobloxian** [Laskyyy/Create-Astral#10]
The cobble gen that uses quadruple compressed andesite uses 
"compressor:single_compressed_andesite" as the result, when it should infact be
"compressor:compressed_andesite"
Due to this error any attempts at generating compressed andesite fail.

**Comment by lrcno6** [comment]
You are right
I created a PR #12 . Wait for accepting
