### ISSUE TITLE
A large part of the mixing recipes are no longer feasible.

### ISSUE THREAD

**Issue by AlphaGaming7780** [Laskyyy/Create-Astral#105]
I'm not sure if it's a bug, but "Andesite Iron Billet" is used in many crafting recipes, so it would be preferable to give it a crafting recipe.

Version of the modpack : GitHub

Code : https://github.com/Laskyyy/Create-Astral/blob/main/kubejs/server_scripts/create.js#L1153

**Comment by AlphaGaming7780** [comment]
Yes, I can work on it.

From what I can see, the recipe already exists, but the time to make it is `null`, which is probably why the recipe cannot be made.

The question is why was the time set to `null` ?

Do you have an idea of a time that would not be too short or too long ?

And what is the unit used for time ? (Ticks, Ms, S, ...)

**Comment by Laskyyy** [comment]
This was a bug on the git version, i've amended create.js to make it load again.
