### ISSUE TITLE
Deployers with shears won't cut grass or leaves

### ISSUE THREAD

**Issue by minecraftothersteve** [Laskyyy/Create-Astral#108]
Since updating from 2.0.3 to 2.0.4b I can't get deployers to cut grass or leaves with shears. I've done multiple tests with them on contraptions and manually cranked, placing the deployer in different positions and orientations, and switching between attack and use modes. I'm able to cut them as expected holding the shears, so it doesn't seem like the grass/leaves are the issue. I haven't tested with ferns or seagrass, but this bug means I have no way to automate biofuel for rockets at the moment.

**Comment by minecraftothersteve** [comment]
Just saw #104 reported, with deployers not working as expected related to FTB claimed chunks. Tested my issue and removing the FTB claim on that chunk resolves it and deployers cut grass again - claimed chunk again and deployers stop working. Will wait for 2.0.4c to see if that fixes this too

**Comment by Laskyyy** [comment]
"/ftbteams server settings [teamname] ftbchunks:allow_fake_players allow"

or

press ] (opens ftbchunks map) --> large map (top left) --> bottom right (server settings)

This'll be applied by default to all future versions, will link questions regarding this back to here just so there is a place to reference with the workarounds right now.
