### ISSUE TITLE
Packwiz-installer : Failed to make HTTP request

### ISSUE THREAD

**Issue by AlphaGaming7780** [Laskyyy/Create-Astral#114]
I got this error :
![image](https://user-images.githubusercontent.com/69048433/232333376-69003257-91d9-4b9b-99ac-f81bac9feacc.png)

To fix it, just add a “s” to the http like this in the README :
`"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://localhost:8080/pack.toml`

**Comment by adamk33n3r** [comment]
I'm having this issue as of today. Super weird cause I've definitely run this before. I didn't even change my prism custom command, it's just now not working. Using `https` does not work for me, a different error.

**Comment by adamk33n3r** [comment]
Interestingly, I just on a whim tried changing the port to `8888` in both the `packwiz serve` command and prism and now it works. Super weird, because running a `curl http://localhost:8080/pack.toml` returned the file, but prism wouldnt work with it. Idk! just glad it works now.
