### ISSUE TITLE
[SUGGESTION] AE2 auto crafting: disable Molecular Assembler only

### ISSUE THREAD

**Issue by quanfornow** [Laskyyy/Create-Astral#119]
From what I heard Pattern and Pattern Provider is disabled to "encourage create (auto)crafting" (Mechanical Crafter?). If so I think this is a good idea to just disable Molecular Assembler instead of the whole auto crafting from ae2. It wouldn't hurt anything and would help neish players like me  who wants a big ME system to do everything.
If this is a bad suggestion plz tell me why it should be disable.

**Comment by Laskyyy** [comment]
Implemented in 2.1
