### ISSUE TITLE
Rubber logs can't be stripped normally

### ISSUE THREAD

**Issue by Rubenazo99** [Laskyyy/Create-Astral#127]
Rubber logs cannot be stripped with axes and can't be used to get bark. Shouldn't it be consistent with the rest of the trees?

**Comment by Rubenazo99** [comment]
https://user-images.githubusercontent.com/97535896/236193534-79fe267e-321f-4bb5-aca1-2ddcdee079ce.mp4

**Comment by Not-Roy** [comment]
This bug also applies to `ad_astra:glacian_log`, `tconstruct:bloodshroom_log`, `tconstruct:greenheart_log`, and `tconstruct:skyroot_log`

**Comment by Laskyyy** [comment]
Roy's commit has this amended ^
