### ISSUE TITLE
Add to modrinth?

### ISSUE THREAD

**Issue by swz-git** [Laskyyy/Create-Astral#128]
Why isn't this modpack on [modrinth](https://modrinth.com/)? I feel that it is a much faster and more convenient platform

**Comment by Auxioni** [comment]
Because it uses mods from Curseforge, and Curseforge doesn't allow the MrPack format to use their links.

Your can read more about this [here](https://blog.modrinth.com/p/modpack-changes)

**Comment by Laskyyy** [comment]
It may be on the table for the future
