### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by lrcno6** [Laskyyy/Create-Astral#13]
Is it under AGPL-3.0 as telled in CurseForge? https://www.curseforge.com/project/681792/license
dont make us worried if u turn it ARR

**Comment by JieningYu** [comment]
Probably it will turn to ARR as Create: Astral 2.0 removed all licensed textures from Cabriclaity under AGPL/GPL 3.0 so it's free to change its license now.

**Comment by lrcno6** [comment]
I know it could, and i wonder if it would

**Comment by Laskyyy** [comment]
I am not informed well on licensing, and I prefer keeping it relatively open for contribution from the community. What would be the right place to find which license to choose in this case?

**Comment by lrcno6** [comment]
You mean where to put the LICENSE file?
I think the root of repo is an option
That GitHub can analyze the LICENSE file matters

**Comment by lrcno6** [comment]
It cannot mean how to choose which LICENSE to use right ... ?

**Comment by Laskyyy** [comment]
https://github.com/Laskyyy/Create-Astral/commit/f88e5acf8d5b9ddf7f2cb350fb4b57f5d672362e
