### ISSUE TITLE
Quest Book Missing - Can't Craft A New One

### ISSUE THREAD

**Issue by SupplyBlock** [Laskyyy/Create-Astral#132]
My Quest Book got destroyed and I cannot seem to be able to craft a new one from a book.

Has anyone else had this issue?

Thanks, any help would be appreciated.

Love the Modpack!

**Comment by genesy** [comment]
you can use "J" to open the quest ui without the book.

**Comment by Laskyyy** [comment]
I'll probably add a fallback just in case
