### ISSUE TITLE
Issues with createaddon

### ISSUE THREAD

**Issue by Etek2** [Laskyyy/Create-Astral#135]
I am having issues setting up a create astral server. The createaddon mod is dependant on certain versions of flywheel, one of which, flywheel-forge-1.18.2-0.6.8 is in the modlist but it seems to think it is not the correct version. Any potential with this is appreciated. I plan on raising the same issue on the flywheel page. ive tried multiple versions of flywheel available on curseforge and no luck.

**Comment by Laskyyy** [comment]
You should never need flywheel in a fabric modpack as it is bundled with create fabric. 
Are you sure you are using an unmodified server pack and using fabric loader 0.14.14 (and not forge loader)

**Comment by Etek2** [comment]
After installing fabric I am able to get Minecraft to load up properly. However, even after doing a fresh install of the server pack, when I try to connect to the server I get an error that says "This server has mods that require Forge be installed on the client. Please contact your server admin for more details." Any further help would be appreciated.
