### ISSUE TITLE
Config error with createaddition

### ISSUE THREAD

**Issue by minecraftothersteve** [Laskyyy/Create-Astral#136]
After being really confused why my machines weren't getting enough power even though I've been using spools of gold wire to hook them up, I saw in the code that the connectors are configured to only transfer 32fe/t. I opened the in-game config editor and on the page for createaddition > common > Wires for 3 of the 4 settings it's showing "Impl missing - Long". I've manually edit the config file to change the connector output value, but it'd be great to see this fixed for the in-game config editor so we can make changes more easily.

**Comment by Laskyyy** [comment]
I believe this is an error on the createaddition side as their fabric port is behind and unmaintained.

It used to work as of 0.4 but the switch to create 0.5 broke a lot of that config it appears.

**Comment by Laskyyy** [comment]
[01d274a](https://github.com/Laskyyy/Create-Astral/commit/01d274a05becca841fada85e093e70d3ac96a241)
