### ISSUE TITLE
Blowing a fan against a cast bassin/table should decrease the cooling down time

### ISSUE THREAD

**Issue by StealthyKamereon** [Laskyyy/Create-Astral#140]
I think it could be sweet that having a fan blowing against a casting table or bassin increase its speed :)
I'm not sure about the complexity of the task though :D

**Comment by Erdragh** [comment]
Welp that's asking modpack developers to add compatibility between two different mods, one of which (tinkers/Hephaestus) isn't getting updates for the version in use anymore.

I could try looking into making it possible, but it's a big ask.

**Comment by Erdragh** [comment]
I'm closing this now, because I don't think I'll ever get around to implementing it. Sorry!
