### ISSUE TITLE
Can’t not complete any quest

### ISSUE THREAD

**Issue by NavEavn** [Laskyyy/Create-Astral#143]
My friend set up a server to play on, but we encountered a problem. When we tried to complete a quest after obtaining the required item, we were unable to complete . The quest could only be completed when we gave the item to the player hosting the server.

**Comment by Erdragh** [comment]
Check whether you're all in the same FTB Team, so you can complete quests together.

You can access the teams GUI using the button with the people icon in your inventory. Alternatively you can use the FTB teams command.

**Comment by Erdragh** [comment]
Closed as unresponsive. If you still have the issue, reopen the issue.
