### ISSUE TITLE
Hopefully the recipe for smeltery controller can be added back

### ISSUE THREAD

**Issue by Qi-Month** [Laskyyy/Create-Astral#178]
Hopefully the recipe for **smeltery controller** can be added back
Because it's gonna be hard for us TCon players

**Comment by Erdragh** [comment]
Nope, it's intentionally disabled. You're supposed to use and learn Create with this pack, which also includes doing alloying with Create mixing. 
This isn't inherently obvious from the quest book right now tho, but will be improved in the next update.

**Comment by Qi-Month** [comment]
> Nope, it's intentionally disabled. You're supposed to use and learn Create with this pack, which also includes doing alloying with Create mixing. 
> This isn't inherently obvious from the quest book right now tho, but will be improved in the next update.

Oh, sorry. In fact, I fancy the large capacity of the smelting furnace, not for the alloy. I knew that alloys could not be made, but the capacity of the small stove was too small, which greatly reduced our work efficiency

**Comment by Erdragh** [comment]
You can still make the foundry lager on in the pack.
