### ISSUE TITLE
Inability to make seared stone via melter despite quests saying you could

### ISSUE THREAD

**Issue by FnigePython** [Laskyyy/Create-Astral#18]
In the quest "Get Casting", it states: "By the way, you can now make seared bricks by melting clay and pouring it into an ingot cast". Upon trying this out, you are left with the realisation that this does not work. Instead you are given bricks.

Im guessing this is unintentional given the quest text. The fix would be to change the molten clay + stone button recipe in the melter to output seared bricks instead of normal bricks

**Comment by lrcno6** [comment]
pour molten clay into stone-like block to craft seared-stone-like block
melt seared-stone-like block into fluid seared stone
pour fluid seared stone into ingot cast to craft seared brick

**Comment by FnigePython** [comment]
Oh yeah we found that workaround. Said workaround has some funny side effects but the the molten clay + button recipe making bricks instead of seared bricks still doesnt feel intentional

**Comment by lrcno6** [comment]
if u want convient, smelt the groud
if u want lower the cost, do what i have told

**Comment by FnigePython** [comment]
Yeah true, still seems unintended though

**Comment by inmourning** [comment]
the intention was to.. remove smelteries as a whole. uh oh.
