### ISSUE TITLE
a hard cap on breeding animals making it impossible to make an effective animal farm

### ISSUE THREAD

**Issue by WTFolsen** [Laskyyy/Create-Astral#192]
i would like for the cap to be removed and have vanilla capabillities for making animal farms. If not could you tell me if there is a config or anything i could change?

thank you

**Comment by Erdragh** [comment]
@Laskyyy weren't the animal caps only on the official servers for performance reason? They should not be in the distributed packs.

**Comment by Laskyyy** [comment]
Newest server pack being uploaded will not include our servercore like last time, expect it up ~30 mins after I post this comment.
