### ISSUE TITLE
Missing Serverpack on curseforge

### ISSUE THREAD

**Issue by DenuxPlays** [Laskyyy/Create-Astral#197]
I wonder how to get the Serverpack for the Version `2.0.5`???
On curseforge there isn't a download for it availabel:
![image](https://github.com/Laskyyy/Create-Astral/assets/83671398/eaa2a917-1aa1-449f-a585-9e7013a2ba66)

**Comment by Laskyyy** [comment]
Was denied by CF, working on uploading a replacement since a few important mod versions we use can no longer be uploaded as jars to CF.

**Comment by nvl-ez** [comment]
@Laskyyy will there be a release here in github for the server files, or will it be uploaded somewhere else?

**Comment by Erdragh** [comment]
Update 2.0.5b has now made the server pack available on curseforge, with special instructions for installation. Follow those when installing or updating.
