### ISSUE TITLE
Moon Rendering Bugs when upgrading world from 2.0.4c to 2.0.5

### ISSUE THREAD

**Issue by Crazyafk** [Laskyyy/Create-Astral#203]
I recently updated my world from modpack version 2.0.4c to 2.0.5. Worked fine until i visited the moon.
![image](https://github.com/Laskyyy/Create-Astral/assets/61631722/fffa81c4-c1f4-4b33-a48f-f5baa2ac22f7)
^i got these messages in chat. screenshot taken in overworld immediately afterwards. latest.log attached.
[latest.log](https://github.com/Laskyyy/Create-Astral/files/12386344/latest.log)

in addition to the strange chat messages, create moving parts and contraptions were invisible, and there was a complete lack of shading., as shown below.
![image](https://github.com/Laskyyy/Create-Astral/assets/61631722/68b9d62a-49bf-43f9-a1a3-a3e88263eb0a)

Any ideas if this is something you can fix in a patch or if i can fix it myself are much appreciated

**Comment by codewarrior0** [comment]
Can reproduce on v2.0.5. Error occurs when a Create contraption tries to render, which can be done as simply as placing a Windmill Bearing on the moon.

**Comment by Laskyyy** [comment]
Should be fixed in 2.0.5b
