### ISSUE TITLE
Fuel refinery not working 

### ISSUE THREAD

**Issue by LordSluggo** [Laskyyy/Create-Astral#206]
How to Reproduce?

Place a fuel refinery (Ad Astra) with an input for oil
Place an electrical generator (Ad Astra, Tech Reborn)
Verify both oil and electricity are loaded into the refinery
Observe oil not being converted into fuel

Version 1.0.9 

Fabric 0.14.14

![262518551-0b8f337a-790d-4643-aa14-47393b3e40ec](https://github.com/Laskyyy/Create-Astral/assets/51515044/b83cc008-3c77-4a87-abcf-bea91a447489)

**Comment by Erdragh** [comment]
That is intended behavior. Follow the quest book. You are not supposed to use the fuel refinery from ad astra. Its recipe is a leftover from an older version and will be removed.
