### ISSUE TITLE
Stuck in Immersive Aircraft

### ISSUE THREAD

**Issue by TorgoTheWhite** [Laskyyy/Create-Astral#208]
I'm having trouble with Immersive Aircraft since updating my server (Create Astral 2.0.5). 

I can place aircraft and sit in aircraft, and WASD seems to work, but I can't press Space to start the engine and I can't exit the craft with R. I'm stuck in the seat until a creeper happens along to blow up the plane or I use an op command to teleport out. 

Space bar is bound to "Up" and R key is bound to "Dismount." Neither one works. I've restarted my server and client several times. Can anyone help?

**Comment by Erdragh** [comment]
Does this still happen after the 2.0.5b update? We updated immersive aircraft because of a security vulnerability.

**Comment by Erdragh** [comment]
Closing this issue as unresponsive. If you respond after this, please reopen it.
