### ISSUE TITLE
shimmer isnt able to enter create spouts or tanks from create pipes

### ISSUE THREAD

**Issue by ANoxInABox** [Laskyyy/Create-Astral#214]
so i made a pipeline from my nearest shimmer lake and when i try connecting the pipes to create storage systems like spouts or tanks it wont transfer into them
![2023-08-26_17 52 43](https://github.com/Laskyyy/Create-Astral/assets/66884773/e08585b9-3123-4ef4-9a08-75e47d1db85a) 
heres an image of me trying to connect the pipe to a spout and nothing is going through and nothing is in the spout

**Comment by ANoxInABox** [comment]
when i tried to connect it to the tank to the left nothing went into it either even with a pump going directly into it

**Comment by ANoxInABox** [comment]
oh and the version i am using is 2.0.2

**Comment by ANoxInABox** [comment]
ok so i went to get the shimmer into buckets manually and it filled some of them partially like 74mb

**Comment by ANoxInABox** [comment]
so it only enters when its not in simulation distance somehow

**Comment by ANoxInABox** [comment]
i opened to lan and now it works

**Comment by Erdragh** [comment]
May I ask why you're on 2.0.2, when the latest version is 2.0.5b? Does it happen with that version too?

**Comment by Erdragh** [comment]
Closing this as unresponsive. If you do come back to answer it, please reopen the issue.
