### ISSUE TITLE
Crash on mouse hover

### ISSUE THREAD

**Issue by Nekrowolf** [Laskyyy/Create-Astral#219]
Hello. Version 2.0.5b When you hover the mouse over an open quest in this tab of the quest line, the world is saved and crashed.
![Квест](https://github.com/Laskyyy/Create-Astral/assets/143880411/3579f5e4-62bd-4914-bb83-4dceae6161cf)
![Квест2](https://github.com/Laskyyy/Create-Astral/assets/143880411/3d917357-fa4e-4b5b-8d3f-37ce8d5104ad)

**Comment by Erdragh** [comment]
Could you provide the crash report for the crash in question?

**Comment by Erdragh** [comment]
Closing this because there was no further response. If you or somebody else wants to continue this discussion, feel free to reopen the issue.
