### ISSUE TITLE
Let non-creeper explosions damage other entities

### ISSUE THREAD

**Issue by deathrobloxian** [Laskyyy/Create-Astral#22]
Environmental creeper config in question:

environmentalcreepers.json

"disableOtherExplosionEntityDamage": true,

The config being true prevents tnt and other explosions from being damaging to players and other entities.  So setting it to false would allow for normal behavior of explosions.   Just find it weird why this config is set to true in the 1st place.

**Comment by Laskyyy** [comment]
https://github.com/Laskyyy/Create-Astral/commit/ebf512dbf8954d2afd72c7c14e32870df9cd1f1a
