### ISSUE TITLE
Problem with crashing in the modpack

### ISSUE THREAD

**Issue by cake9019** [Laskyyy/Create-Astral#220]
Whenever i play the modpack and my internet connection crashes, it always says timed out. i tried different ways of installing the modpack, switched accounts, reset my connection, rebooted the server, but the only way to fix it rn is to delete the whole world and create a new one which would mean losing all my and my friends' progress. Please somebody help.

**Comment by Erdragh** [comment]
Could you provide a latest.log for both the client and the server? Right now there's very little information to go on.

**Comment by Erdragh** [comment]
I will close this issue because there was no response. If you upload the log, please reopen it.
