### ISSUE TITLE
Dry Rich Soil Farmland side texture is missing

### ISSUE THREAD

**Issue by MrNachoWagon** [Laskyyy/Create-Astral#224]
![Missing texture top](https://github.com/Laskyyy/Create-Astral/assets/61102608/39d29436-5c1e-4564-9971-d1e811a85147)
![Missing texture bottom](https://github.com/Laskyyy/Create-Astral/assets/61102608/b2cca6e2-c8d3-43b8-b663-14f41f36ed1c)

The top and bottom textures are there, and there are also no missing textures when it's wet.

(Running on the latest version v2.0.5b, and haven't made any modifications to the pack.)

**Comment by HyperRaccoon13** [comment]
okay fixed with texture pack. (i think lol)
[Rich Farm Fix.zip](https://github.com/Laskyyy/Create-Astral/files/12719315/Rich.Farm.Fix.zip)
![image](https://github.com/Laskyyy/Create-Astral/assets/68512889/56c18cf9-2a43-4d37-a391-c052fea1622c)

**Comment by MrNachoWagon** [comment]
Thanks, the fix works a treat.

Out of curiosity, would you happen to have any idea why the texture wasn't there in the first place? Cause this should have just been there within FD's textures, and to my knowledge none of the mods textures are modified for the pack.
Just seems to be a very odd thing to be missing.

**Comment by MrNachoWagon** [comment]
Wait, my bad, it's to do with the model, not the texture. Still, it seems very odd to be broken.

**Comment by HyperRaccoon13** [comment]
Honestly I'm not sure how just having the 2 model files in/on their own fixes the bug. It just kinda worked

**Comment by The-Shortman** [comment]
Reopening as this issue was never actually fixed in-game

**Comment by The-Shortman** [comment]
Fixed in 2.1.5a by #725
