### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by TheDayDude** [Laskyyy/Create-Astral#23]
On the current version and cannot make:
Vanilla Stonecutters
Create Millstones
Create Windmill Bearings 
Compressed Andesite

And I feel like there may be others at this rate. The above do not have any recipes when you click on them and nothing happens if you try original recipes, despite these being needed for quest progress. I've had to just cheat these in.

**Comment by Laskyyy** [comment]
I can't seem to replicate this on my current dev build or the official server, i'll try reinstalling a fresh v2.0.2 instance tomorrow.

Let me know if this happens on a fresh instance for you also.

**Comment by Auxioni** [comment]
Nope, all of them work on a fresh install of v2.0.2
