### ISSUE TITLE
Tree autofarm problem

### ISSUE THREAD

**Issue by MiniRaptor** [Laskyyy/Create-Astral#230]
Hello, I recently built a tree farm, and came across this thing: tree leaves can break blocks.

It so happened that I covered the tree farm with blocks, it’s more aesthetically pleasing to me. It also happened that there was water above the tree farm. When the tree grew, it was able to break through the ceiling, which, by the way, was made of obsidian. The water rushed in and washed away all the seedlings.

**Comment by Erdragh** [comment]
Which species of tree?

**Comment by MiniRaptor** [comment]
> Which species of tree?

rubber tree

**Comment by Erdragh** [comment]
Yeah I expected that. The Tech Reborn tree is wonky. There isn't a lot we can do about this since it's a coding issue by TR.
Sorry
