### ISSUE TITLE
Modpack v1.2

### ISSUE THREAD

**Issue by Qi-Month** [Laskyyy/Create-Astral#232]
Will the 1.2 version of this Modpack be made available for download again? Sometimes I want to revisit old versions.

**Comment by Erdragh** [comment]
This was resolved on the discord, right?

**Comment by Qi-Month** [comment]
> This was resolved on the discord, right?

Where is it, please?

**Comment by Qi-Month** [comment]
> This was resolved on the discord, right?

Sorry, I didn't see it in curseforge

**Comment by Erdragh** [comment]
Yeah, that's intentional.

**Comment by Qi-Month** [comment]
> https://discord.com/channels/813762487253860373/1041387620950884414/1155610901089620038
> 
> If I'm not completely blind, laskyyy @-ed you.

OK, let me see

**Comment by Qi-Month** [comment]
> https://discord.com/channels/813762487253860373/1041387620950884414/1155610901089620038
> 
> If I'm not completely blind, laskyyy @-ed you.

I am a Chinese, hope you will not discriminate against us. I am here to thank you!

**Comment by Erdragh** [comment]
Not at all! I also still have a 1.2 world from back before I was a dev. It is definitely nice to go back and revisit that. Have fun!

**Comment by Qi-Month** [comment]
> https://discord.com/channels/813762487253860373/1041387620950884414/1155610901089620038
> 
> If I'm not completely blind, laskyyy @-ed you.

Your Modpack is not very popular in China, but there are many players like your Modpack (including me)!
