### ISSUE TITLE
I have my own server and I have a few questions to ask

### ISSUE THREAD

**Issue by Hlianga** [Laskyyy/Create-Astral#233]
1.Is there no formula for heat-resistant metal rockets?
2. How to get to the end of the land (end world)
3. Can the AE template provider formula be opened for players and have an impact? （ae2:pattern_provider）

**Comment by Erdragh** [comment]
Ok I'm gonna try and answer these questions under the following assumptions:
"Heat resistant metal" refers to the calorite rocket. "The end of the land" refers to the end dimension. 

1. There is not, currently. There will be in the future.
2. The end is work in progress. It will be reachable in the next major update (2.1) and you will most likely use the calorite rocket to get there.
3. The AE2 integration is being overhauled for 2.1. A part of that will be reenabling pattern providers. The current plan is to allow players to use autocrafting, but without molecular assemblers.

**Comment by Erdragh** [comment]
Closing this because there hasn't been a response.
