### ISSUE TITLE
Missing recipes after upgrade

### ISSUE THREAD

**Issue by Ekagrah** [Laskyyy/Create-Astral#235]
Upgraded from 2.0.3b to 2.0.5b. Followed the text in server pack (running a dedicated server) to copy over Vinery and Hephaestus. Unable to see recipe for Sturdy armor pieces - but they do show in search. There are quite a bit of errors for kubejs but searching the log file didn't show anything obvious related to this. We have tried picking up resources again to see if it needed to be triggered but no success yet. I loaded single player and everything seemed normal there. Returning to the multiplayer server and knowing the recipe, it is uncraftable. Same issue with steel ingots. Will update with any further recipe issues.

This causes an issue with progression in Chapter 4 and crafting the lead-lined space gear.

**Comment by Ekagrah** [comment]
I use a headless linux server. My command history tells me I had deleted everything in the folder, added the new server files and fabric jar, then copied over the files from a backup (my own backup solution for world files and config files). Seems that this backup contained a "kubejs" folder. I'll rebuild the server and exclude that from the backup restore.

**Comment by Erdragh** [comment]
If that solves the issue, please close this issue.
