### ISSUE TITLE
[2.0.5b server] No apparent usage for Scrap from Tech Reborn

### ISSUE THREAD

**Issue by wafflecomposite** [Laskyyy/Create-Astral#252]
I made a TechReborn's recycler hoping to recycle junk into something useful.  
I was able to get a scrap from it despite `scrap` not showing neither recipes or usages in REI.  
However, it's unclear how can I further proceed to crafting an actually useful `scrap box` from it (doesn't show a recipe either). Default recipe from tech reborn wiki doesn't seem to work. Recycling is not mentioned in questlines whatsoever, at least as far as 3.5 stage goes.

![image](https://github.com/Laskyyy/Create-Astral/assets/28294714/4a8d8afe-57fc-4493-8cdd-7e145073089f)

It this intentional? Is there an other recipe? If not, is there a way to fix that with some config edits on the server side?

Thanks!

**Comment by Laskyyy** [comment]
Not just now, but the next version will have scrap and it's purpose adjusted back to what you're expecting, we've since been able to update the loot tables.
