### ISSUE TITLE
Create: Alloyed Guns integration

### ISSUE THREAD

**Issue by Mattslayer2006** [Laskyyy/Create-Astral#257]
Integrate Create: Alloyed Guns to the modpack as I think it will fit nicely in the modpack and give more options for long range combat

**Comment by Erdragh** [comment]
We can't integrate a mod into a 1.18.2 fabric modpack that only has one version available, which is for 1.19.2 forge.

https://www.curseforge.com/minecraft/mc-mods/create-alloyed-guns/files
