### ISSUE TITLE
Odd dungeon spawning behaviour.

### ISSUE THREAD

**Issue by a-jennings** [Laskyyy/Create-Astral#26]
Travelling through the world I came across strange dungeon spawning behavior with floating generation, and an open to air zombie spawner.

Seed: 5800667603343744096
Co-ords: -305, 100, -52
Mod version: 2.0.2

Images attatched:
![2023-03-01_20 54 24](https://user-images.githubusercontent.com/16850455/222263397-7f5e2307-45a3-4742-805c-9d540e06e4ca.png)
![2023-03-01_20 54 35](https://user-images.githubusercontent.com/16850455/222263419-67ba6560-9f6e-4bc0-842d-55214b228ec3.png)

**Comment by a-jennings** [comment]
This similar generation also appears at the following coordinates in the same seed: -328, 70, -985

**Comment by Laskyyy** [comment]
AstralRails datapack has been adjusted to account for this and prevent buggy worldgen from happening now
