### ISSUE TITLE
nether bug

### ISSUE THREAD

**Issue by mizancraft** [Laskyyy/Create-Astral#263]
hi I made a homemade server with the server pack that downloads by the curseforge app, I made a normal survival, and I made the nether portal and I can't go to the nether, my friend try it, but he can't too, so I made a new world and nothing, so I can't get to the nether, causing that I can't proced the survival

**Comment by Erdragh** [comment]
Follow the quest book. The nether's resources are scattered on the various planets from ad astra. The nether and the end itself are disabled.
