### ISSUE TITLE
New main menu. by shortman

### ISSUE THREAD

**Issue by Infern0-b0b** [Laskyyy/Create-Astral#275]
when "mousing over" all of the icons in the main menu the text that pops up moves with the mouse.

For the "Open Accessibility Options" button it does not move with the mouse. (this is the problem).

I think it is because the text is long and pushes against the side of the screen.

perhaps switch that button with one on the left?

-b0b

**Comment by Erdragh** [comment]
I can't reproduce this, can you provide a video?

**Comment by Infern0-b0b** [comment]
https://github.com/Laskyyy/Create-Astral/assets/140122400/fa6f6f90-2187-4b90-b1b3-dd656b146ebe

I had to record in 480p and 30fps to make the file small enough to upload.

As you can see near the end when I hover over the "Open Accessibility Options" button. the text that pops up does not move from left to right, only up and down. It makes sense it wouldn't be able to move right because its on the edge of the screen, but  I don't know why it cannot move left.

-b0b

**Comment by Erdragh** [comment]
I couldn't reproduce this on my ultrawide monitor, so it's most likely just that the text is too long. This seem very minor and not worth fixing imo.
