### ISSUE TITLE
Will there be a update?

### ISSUE THREAD

**Issue by Gamenait** [Laskyyy/Create-Astral#282]
Will Create Astral get a update? Maybe newer version of create plus some new create addons like steam and rails?

**Comment by Erdragh** [comment]
Man we're at the stage we get issues asking for an update :(. 

Yes, there will be an update. You can check for yourself by looking at the `Astral-Experimental` branch. And yes, it has the latest create and steam'n'rails.

Be patient, we don't get paid for what we do.

**Comment by Gamenait** [comment]
Thanks for a response. I am writing it in issues becose on the github page it says to write here questions. And I know you arent paid, I was just interested if it is still in development. Love this modpack.
