### ISSUE TITLE
[Suggestion] More Trinket Slots 

### ISSUE THREAD

**Issue by HunterDragnel** [Laskyyy/Create-Astral#287]
currently every trinket goes in the face slot, so you can only have one at a time which you usually have the Create goggles in meaning you cant use anything else. a couple more slots would be fantastic. maybe a back slot for the backpack because it takes up the chest plate slot and doesn't hold any items if its not there. and the belt and aglet trinkets going in the face slot just doesn't make sense.

**Comment by Laskyyy** [comment]
Marking as complete.
