### ISSUE TITLE
[Bug]: Lunar Pipelines do not exist?

### ISSUE THREAD

**Issue by Xfel** [Laskyyy/Create-Astral#379]
### Bug Description

I've reached chapter 3 and it now tells me to find the pipeline structure on the moon.

However, there seems to be no such structure. At least I could not find anything matching the name in the explorer's compass.

I did run into a ruined powerplant thingy which had a blaze spawner, so I don't really need it either.

### Version

2.1

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by Xfel** [comment]
Update with 2.1.1 it seems now it has been changed to require a blaze rod, which is better but does not work when playing peaceful.

**Comment by LucaSch1910** [comment]
Lunar Pipelines dont exist anymore, this has been confirmed by discord mods.

**Comment by Laskyyy** [comment]
2.1.3 quest book should be even clearer about this, we didn't scrub pipeline mentions as well as we thought...
