### ISSUE TITLE
Inacurate "Bedrock Stone Generator" quest description

### ISSUE THREAD

**Issue by Tlotro** [Laskyyy/Create-Astral#39]
the quest says that granite/andesite/diorite generate at 20% and stone at 40% over bedrock.
But the CobbleGen mod config says that stone generates 91,7431% of the time and other rocks 2,75229% of the time each over bedrock.
![image](https://user-images.githubusercontent.com/50557602/223824434-4ca490f3-eb27-4c6a-b6c0-73f18a44a037.png)
![image](https://user-images.githubusercontent.com/50557602/223824744-0370dec8-9a50-4d12-991a-29ec4cdad392.png)
![image](https://user-images.githubusercontent.com/50557602/223824803-3c3888fe-d494-4e7e-8962-019896c0e727.png)
observation confirms that config works as intended

**Comment by Laskyyy** [comment]
https://github.com/Laskyyy/Create-Astral/commit/78c8ea0042210fde008188ea93c7e4f99b06f786
