### ISSUE TITLE
[Bug]: Fluids don't work

### ISSUE THREAD

**Issue by Jotunn9025** [Laskyyy/Create-Astral#391]
### Bug Description

When any other players or me jump into water on a server. It behaves like it doesnt exist. Fall damage is taken. We can still breathe.  Similar issue in lava. 
![2024-10-17_23 10 43](https://github.com/user-attachments/assets/41b145c1-18d5-4d60-9e74-1803c1467733)
![2024-10-17_23 12 26](https://github.com/user-attachments/assets/1ecef01a-da45-4381-8358-a990e6723ff9)

### Expected Behavior

Can swim in water burn in lava. Limited breathing ability. Negated fall damage

### Version

2.1.1

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by LucaSch1910** [comment]
I can confirme that was told by mods in the official discord server that these structures don't exist. You must select the mission as complete and have to find the broken reactors in which there are blaze spawners.

**Comment by Jotunn9025** [comment]
Make sure you follow the readme and install the vinery and hephaestus mods from clientside into server mods folder to fix.
It works now
