### ISSUE TITLE
[Bug]: all tinkers construct (Hephaestus) tools are white

### ISSUE THREAD

**Issue by LiamHaste** [Laskyyy/Create-Astral#401]
### Bug Description

all of the tools and tool parts for tinkers construct are white

### How to Reproduce?

look at tools

### Expected Behavior

they should have color

### Version

2.1.1

### Logs or additional context

none

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by dyluuuuun** [comment]
+ if you add a modifier to any weapon/tool it loses its texture completely (the purple and black squares show up)

**Comment by LiamHaste** [comment]
ya i saw that too
