### ISSUE TITLE
[Bug]: A quest reward wrong blueprint

### ISSUE THREAD

**Issue by mangke01** [Laskyyy/Create-Astral#405]
### Bug Description

In the quest "You spin me right round..." (quest ID: 673DC1F22D2F790D), the reward of this quest named "Distillery"blue print, but it's actually the Shimmer Refinery blue print.

### Version

2.1.1

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by LucaSch1910** [comment]
Same issue here

**Comment by Laskyyy** [comment]
Will be included in 2.1.2
