### ISSUE TITLE
[Bug]: Beetroot collection quest is titled "Gather Corn"

### ISSUE THREAD

**Issue by BgueC6595** [Laskyyy/Create-Astral#412]
### Bug Description

![image](https://github.com/user-attachments/assets/e978e3ba-e2b4-4f26-9273-5e66a7534f8b)

### How to Reproduce?

1. Open Quest Book
2. Go to chapter 0.5
3. Look at the "Gather" quest for beetroot

### Expected Behavior

No corn

### Version

2.1.1

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by Laskyyy** [comment]
Will be included in 2.1.2
