### ISSUE TITLE
[Bug]: Beds do not set the spawn point

### ISSUE THREAD

**Issue by AurySystem** [Laskyyy/Create-Astral#433]
### Bug Description

Beds currently do not set the player spawn, even when correctly sleeping in them overnight. This does not seem to be intended behavoir

### How to Reproduce?

1. Place or find a bed
2. wait for night
3. sleep in the bed
4. die and respawn

### Expected Behavior

The player spawn point should be moved to the bed.

### Version

v2.1.2

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by monkyman64** [comment]
This is caused by the mod "Kubejs Additions", removing the mod from the pack is the current recommended course of action.

**Comment by ChiefArug** [comment]
If its KJS Additions causing it then it should be fixable with a KJS script
