### ISSUE TITLE
"Get Luckier" Quest unable to complete

### ISSUE THREAD

**Issue by KajesLorian** [Laskyyy/Create-Astral#48]
Tried tossing and picking back up items, and relogging, but nothing works. I was even able to upgrade my tool, but it still won't complete. What are these 4 hidden dependencies?

![image](https://user-images.githubusercontent.com/16963626/224467929-ab75a654-6906-40bf-bc40-e3b794a0c083.png)

**Comment by Laskyyy** [comment]
Someone must've added extra dependencies by accident, it'll be corrected for future releases

**Comment by Laskyyy** [comment]
https://github.com/Laskyyy/Create-Astral/commit/212c533a6f4ebcc75c1111e0872f69a9ed2b0321
