### ISSUE TITLE
Certus Quartz Dust has Millstone and Crushing wheel recipes that fail to display

### ISSUE THREAD

**Issue by SirCatolot** [Laskyyy/Create-Astral#49]
![2023-03-12_23 44 16](https://user-images.githubusercontent.com/91162010/224603405-b7ea1a0e-e7be-457f-a73a-ea31bd2b57ce.png)
![2023-03-12_23 44 17](https://user-images.githubusercontent.com/91162010/224603408-57ae27c8-25c4-4072-805b-bf40a460fe72.png)

**Comment by Laskyyy** [comment]
https://github.com/Laskyyy/Create-Astral/commit/d1bd1d2ed99574e12ff724344fbdedba890c945e
