### ISSUE TITLE
Crash after placing depot

### ISSUE THREAD

**Issue by Codebreakerblue** [Laskyyy/Create-Astral#54]
After equipping a depot from a toolbox and placing it, the game crashed.
Here's the crash log:
[crash-2023-03-14_13.54.02-client.txt](https://github.com/Laskyyy/Create-Astral/files/10973213/crash-2023-03-14_13.54.02-client.txt)

**Comment by Codebreakerblue** [comment]
The game crashed again soon after, when I took the stack of depots out of the linked hotbar slot and replaced it with a stack of oak planks.

[crash-2023-03-14_14.01.23-client.txt](https://github.com/Laskyyy/Create-Astral/files/10973264/crash-2023-03-14_14.01.23-client.txt)

**Comment by Erdragh** [comment]
Has this been resolved by updating to the latest version of the modpack? (2.0.4c)

**Comment by Codebreakerblue** [comment]
I haven't had this crash since updating, seems to be fixed 👍
