### ISSUE TITLE
Move all, move similar

### ISSUE THREAD

**Issue by jeytee84** [Laskyyy/Create-Astral#56]
Similar functonality to what was included in InvTweaks i think, moving the entire inventory with space-click and moving similar items with shift-space-click. I think its possible in InvProfilesNext, just not sure how.

**Comment by Auxioni** [comment]
You can set a keybind for it in the settings of that mod

**Comment by kil0byt3** [comment]
I would love this as default, or just emulating all "classic" Inventory Tweaks features/keybinds by default <3
