### ISSUE TITLE
Using Piggybackpack while wearing a backpack deletes all contents of backpack.

### ISSUE THREAD

**Issue by NekoSpirits** [Laskyyy/Create-Astral#60]
Using the Hephaestus Piggybackpack while wearing a Cammie's Wearable Backpack backpack, will delete all the contents of the backpack, and put the backpack on your inventory.

![image](https://user-images.githubusercontent.com/20034469/226445173-56f3b172-b6f2-4125-8365-6185f50a6ff7.png)
![image](https://user-images.githubusercontent.com/20034469/226445265-f4643660-3a2f-4841-8b45-0efd6b5c5cc7.png)
![image](https://user-images.githubusercontent.com/20034469/226445346-ecd0aa9c-ad5c-488a-be8f-d243ea7c3c9c.png)

**Comment by Laskyyy** [comment]
Marking as complete, it isn't fixed but the recipe for piggyback is temporarily removed in 2.0.4c and we'll be switching to a new backpack mod (travellers) in v2.1, which has proven to be way less likely to bug out like this!
