### ISSUE TITLE
Giving Fuel Bucket to strawed Blaze Burner causes client crash

### ISSUE THREAD

**Issue by CarlSmotricz** [Laskyyy/Create-Astral#64]
The Blaze Burner can be made blue (i.e. "high heat") by giving him a Fuel Bucket. But to "properly" automate the Burner, it's recommended to give him a Straw, which changes his appearance and allows him to accept liquid fuel via Pump/Fluid Pipe.

Bug 1: This doesn't work; Fuel by pump results in the same "normal heating" state as Charcoal. The Burner lights up but does not turn blue!

Bug 2: Right-clicking on a Straw-using Burner in the "normal heating" state with a Fuel Bucket crashes the client.

I haven't tested whether a quiescent ("off") Burner will also crash the client if right-clicked with a Fuel bucket.

**Comment by Not-Roy** [comment]
This appears to be fixed in Create Astral 2.0.4 because Create Crafts & Additions was updated

**Comment by Erdragh** [comment]
If it’s fixed I’m going to close this issue as such
