### ISSUE TITLE
[Suggestion] Replacing plates with sheets

### ISSUE THREAD

**Issue by legoatoom** [Laskyyy/Create-Astral#65]
# Plates / Sheets
Create has sheets. Ad Astra & Tech Reborn have plates.
It is a bit inconsistent and redundant to have both a `iron_sheet` and `iron_plate` (both ad astra & tech reborn have these).
My suggestion would would be wise to remove all the duplicates and keeping only the sheets. And since this is a create themed mod pack, Re-texturing and renaming the remaining "plates" into sheets. 

I already did a few for thermal in the past, but they won't fit. But the casts I can provide.
[Casts.zip](https://github.com/Laskyyy/Create-Astral/files/11041921/Casts.zip)

**Comment by HaloSense** [comment]
I believe absence of tags (or possibly, ore dictionary) in Fabric is to blame... Life would be way easier with those.

**Comment by legoatoom** [comment]
With Kubernetes one can replace the recipes and remove items from REI, and tags can always be added with new datapacks. So I don't think that is a problem.

**Comment by Laskyyy** [comment]
Yeah this can be done relatively quickly if one of us can get around to it, as plates clutter up recipes a fair amount

**Comment by legoatoom** [comment]
I was looking at the changes that would be made, but I came across this something. At the moment `sturdy_sheet` are part of the steel_ingot tag. Meaning that they are crafted with steel into an ingot cast. Is this intentional?

**Comment by Erdragh** [comment]
Implemented via #319
