### ISSUE TITLE
[SUGGESTION] : Replace the current backpack mod with travellers backpack. 

### ISSUE THREAD

**Issue by TheDragonicSlayer** [Laskyyy/Create-Astral#66]
Travellers backpack is out for fabric! Also the current backpack mod takes up your chest slot, as well as it's annoying to use for crafting since it doesn't show the crafted item and you have to actually craft it to see if the recipe works 😭. Travellers backpack has lesser slots, is less buggy, and is more convenient to use! For more info, check out:
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric

**Comment by Laskyyy** [comment]
https://github.com/Laskyyy/Create-Astral/commit/fad14716ddb7dc1a8c6efe87f4f87cf3151ee0cd

Incoming in next version
