### ISSUE TITLE
[SUGGESTION] Add keybind-search  

### ISSUE THREAD

**Issue by Cyphecx** [Laskyyy/Create-Astral#67]
The [Controlling Mod](https://www.curseforge.com/minecraft/mc-mods/controlling/filesl) has a 1.18 fabric version and allows searching in the key bind menu. 
Its pretty nice quality of life feature that should be an easy addition that does not conflict with anything else.

**Comment by Laskyyy** [comment]
Will be included in v2.1 ❤️
