### ISSUE TITLE
[BUG - CRASH] Crash game when placing Straw item in BlazeBurn

### ISSUE THREAD

**Issue by ribolive** [Laskyyy/Create-Astral#69]
When inserting a straw into a Blazeburn on the Create Astral server without modifying any of the mods, the game crashes and the server becomes unresponsive, rendering it impossible to reopen.

Any suggestions on how to restore my server?

**Comment by Laskyyy** [comment]
Liquid blaze burners on the CCA fabric port are all kinds of messed up currently. They're going to be removed in next update, however if the world is crashing on boot when loading the chunk you may need to observe the crash report to find the exact coordinates of the problematic burner, open the relevant region file in an nbt editor like nbtexplorer, and delete the block entity at the coordinates mentioned in the crashlog. Other world editing programs my also be able to pergorm this.
