### ISSUE TITLE
Compass allows very fast travel

### ISSUE THREAD

**Issue by NekoSpirits** [Laskyyy/Create-Astral#70]
Left-clicking/Right-clicking with the compass allows for fast traveling toward where the player is looking. Unsure if this is a bugged interaction or something that is just not documented.

![CompassMovement](https://user-images.githubusercontent.com/20034469/227556856-f9a80d9d-fe39-4af5-9ab7-65b68b825f76.gif)

**Comment by Cyphecx** [comment]
This is a feature of World Edit for OPed players.

**Comment by NekoSpirits** [comment]
User error.
