### ISSUE TITLE
Shimmer crystals

### ISSUE THREAD

**Issue by Peacekeeper2024** [Laskyyy/Create-Astral#78]
In AE2 we used the fluix crystals to make fluix dust which is just renamed to shimmer in this pack. Yet, the shimmer crystals have absolutely no recipes to turn into shimmer dust. Like the seeds are there and everything but you cannot make the dust from the crystals even when you get them. I think it is a little absurd that To get shimmer on a constant level you need to grind out a squid farm, a glowstone farm, and an amethyst farm. Little ridiculous. hope this is a bug and not a feature

**Comment by Laskyyy** [comment]
The above PR will be merged in 2.1
