### ISSUE TITLE
Blaze Burner does not get "super-heated" when using Blaze Cake

### ISSUE THREAD

**Issue by igortsouz** [Laskyyy/Create-Astral#80]
Blaze Burner does not get "super-heated" when using Blaze Cake, being unable to proceed to produce Steel

**Comment by HammerShankiz** [comment]
I'm having the same issue.  Blaze cakes instead set the blaze burner to maximum time duration of normal heating. Super-heated is only obtainable using the creative blaze cake.

**Comment by HammerShankiz** [comment]
actually you can use fuel buckets to get super heated, not just the creative cake. However do not use a straw on the burner as that instantly crashes the game

**Comment by ribolive** [comment]
I have the same problem. Boring that it's the way for me to have more progression. Example: I need that blue burner to do ENGINE. :-(

**Comment by ribolive** [comment]
And it is not possible to continue chapter 4 and pass the mission "**Iron but slightly harder, I reckon**" (where you must do Steel ingot)

**Comment by Mg138** [comment]
Possible cause, in kubejs `startup.js`:

```js
  event.modify('create:blaze_cake', item => {
    item.burnTime = 50000
  })
```

**Comment by Mg138** [comment]
Hmm, that was not it.

**Comment by Mg138** [comment]
Confirmed to be something within kubejs

**Comment by ribolive** [comment]
Mg, how do I compile the code after modification to test in game, any tutorial for that?

**Comment by ribolive** [comment]
> Confirmed to be something within kubejs scripts

Mg, how do I compile the code after modification to test in game, any tutorial for that?

**Comment by Mg138** [comment]
Call us Madeline, we just have links we can't be bothered to change that point to github pages so that we can't really change the username.

You don't compile the code, you just make your changes to the js scripts under `.minecraft/kubejs/` and then restart the game.

**Comment by Mg138** [comment]
Actually-- it's not kubejs, no idea what went wrong in my reproduction step but it's not kubejs, we found another suspicious part tho.

**Comment by Mg138** [comment]
Suspicion: `minecraft/global_packs/required_data/zLaky Core/data/create/tags/items/blaze_burner_fuel/special.json`

**Comment by Mg138** [comment]
Yep. Change it to `{"replace":false,"values":["ad_astra:fuel_bucket"]}`

**Comment by ribolive** [comment]
Thanks Madeline, the `minecraft/global_packs/required_data/zLaky Core/data/create/tags/items/blaze_burner_fuel/special.json` , It appears to be something to set the burn through the bucket fuel. but I managed to get a slight idea of ​​how the modifications are made in the modpack, having a little time I'll take a look here later

**Comment by Mg138** [comment]
We haven't gotten to the point to make steel yet. Is there any point in quest where you need to make Blaze Cakes for super heating?

**Comment by ribolive** [comment]
We were able to do almost everything in the modpack right up until this quest to make steel, we wanted to do it to see what else is in the modpack.

**Comment by ribolive** [comment]
> Yep. Change it to `{"replace":false,"values":["ad_astra:fuel_bucket"]}`

Did you find the Solution??

**Comment by Mg138** [comment]
Yes, change the file content to that if you want to use Blaze Cakes.

I can't seem to find any presence in the quest book telling you that, though, it appears you're simply suggested to use fuel buckets?

@Laskyyy Some clarification on if fuel buckets are intended to be the only super heating source?

**Comment by ribolive** [comment]
> Yes, change the file content to that if you want to use Blaze Cakes.
> 
> I can't seem to find any presence in the quest book telling you that, though, it appears you're simply suggested to use fuel buckets?
> 
> @Laskyyy Some clarification on if fuel buckets are intended to be the only super heating source?



> Yes, change the file content to that if you want to use Blaze Cakes.
> 
> I can't seem to find any presence in the quest book telling you that, though, it appears you're simply suggested to use fuel buckets?
> 
> @Laskyyy Some clarification on if fuel buckets are intended to be the only super heating source?

NIceee, I managed to use this modification

With this change apparently removes the modification of this item that was placed, allowing the use of the blaze cake!

**Comment by Laskyyy** [comment]
Yes there is no other way to heat blaze burners, intended. It's being reworked in 2.1. 
It determined by a tag in create namespace under the datapacks.
