### ISSUE TITLE
1.18.2 游戏崩溃

### ISSUE THREAD

**Issue by ztm9976** [Laskyyy/Create-Astral#83]
[错误报告-2023-4-4_13.14.39.zip](https://github.com/Laskyyy/Create-Astral/files/11144941/-2023-4-4_13.14.39.zip)

**Comment by Mg138** [comment]
Please include the actual crash report generated by a normal Minecraft install that isn't forcibly hacked to use Chinese translations.

**Comment by ztm9976** [comment]
In the subsequent game process, there was no such issue again. Thank you very much for your reply. By the way, how to obtain lead before going to Mars in the game? My progress has been suspended in the third stage due to this.
