### ISSUE TITLE
CTD when right clicking a fluid blaze burner with something

### ISSUE THREAD

**Issue by TehMightyPotato** [Laskyyy/Create-Astral#87]
As the title suggests I'm experiencing a crash to desktop whenever I'm right clicking the fluid blaze burner with something. Empy hands does nothing, but for every item or block I tried it crashes.

Here's the log: https://mclo.gs/s3vBY2X
The actual crash happens here https://mclo.gs/s3vBY2X#L5390

**Comment by Laskyyy** [comment]
Fixed in 2.0.4, which just released about 10 mins ago ❤️

**Comment by TehMightyPotato** [comment]
Well that was certainly fast. Glad you could resolve it!
