### ISSUE TITLE
Recipe for Oxygen Tank is wrong in version 2.0.4

### ISSUE THREAD

**Issue by jonasogren** [Laskyyy/Create-Astral#89]
Recipe for Oxygen Tank (used for crafting Space suit) is using Steel plates in latest version v2.0.4 instead of bronze sheets (as in version v2.0.3).

**Comment by Laskyyy** [comment]
2.0.4b release should fix the issues due to new namespaces which I wasn't aware of in ad astras update. (and some other changes)
