### ISSUE TITLE
Create contraptions do not appear to render in 2.0.4b with shader enabled.

### ISSUE THREAD

**Issue by tomprince** [Laskyyy/Create-Astral#93]
It seems this is *not* related to the upgrade to Complementary Reimagined, as using the shaderpack from 2.0.3b in 2.0.4b has the same effect, and using the shaderpack from 2.0.4b in 2.0.3b does render contraptions.

**Comment by Laskyyy** [comment]
I can't seem to replicate this and it doesn't appear to be common else there'd be many more reports.
