### ISSUE TITLE
Dying in a moon portal causes a grave to appear in the portal, breaking it.

### ISSUE THREAD

**Issue by tomprince** [Laskyyy/Create-Astral#95]
This causes a new portal to be generated on top of the old one, when you go through it again.

It appears this can be fixed by adding the appropriate blocks to `data/yigd/tags/blocks/replace_blacklist.json` (see [here](https://github.com/B1n-ry/Youre-in-grave-danger/wiki#replace-blacklist) and [here](https://github.com/B1n-ry/Youre-in-grave-danger/blob/1.19/src/main/resources/data/yigd/tags/blocks/replace_blacklist.json)).

**Comment by Erdragh** [comment]
@Laskyyy Please confirm whether this fix was implemented

**Comment by Erdragh** [comment]
Fixed in #174
